# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Shawn Hansen
tagline:             'Coding and Coffee'
description:         'General musings on code and the web.'
url:                 http://geekles.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Shawn Hansen
  url:               https://twitter.com/geekles
  email:             shawn.hansen@gmail.com

# Custom vars
version:             1.0.0
