# Site settings
title: Shawn Hansen
email: shawn.hansen@gmail.com
description: "Web and Mobile Developer"
baseurl: ""
url: "http://geekles.com"
twitter_username: geekles
github_username:  geekles

# Build settings
markdown: kramdown
permalink: pretty
